### ISSUE TITLE
关于Openalex的转换的问题

### ISSUE THREAD

**Issue by Noietch** [whuscity/pySparkDemo_OpenAlex#3]
Hello, 在使用官方和本项目提供的转换脚本都出现了一下的问题
```
Traceback (most recent call last):
  File "test.py", line 613, in <module>
    flatten_venues()
  File "test.py", line 307, in flatten_venues
    ids_writer.writerow(venue_ids)
  File "/usr/lib/python3.8/csv.py", line 154, in writerow
    return self.writer.writerow(self._dict_to_list(rowdict))
  File "/usr/lib/python3.8/csv.py", line 149, in _dict_to_list
    raise ValueError("dict contains fields not in fieldnames: "
ValueError: dict contains fields not in fieldnames: 'wikidata', 'fatcat'
```
不知道是不是最新的数据的问题？

**Comment by MarioZZJ** [comment]
我看你好像在 [这里](https://gist.github.com/richard-orr/152d828356a7c47ed7e3e22d2253708d?permalink_comment_id=4383320#gistcomment-4383320) 也留言了，哈哈，可能数据有更新，这个我也没有验证，应该你在那个处理脚本处自己对着报错改一下就好~ 原作者估计没时间维护了

另外这个问题和这个 demo 无关，或许不应该在这里提 issue ~

**Comment by Noietch** [comment]
确实，主要脚本有点小毛病不知道会不会影响后续的工作
